version: "3.8"

networks:
  kasirin:
    driver: bridge

services:
  webserver:
    networks:
      - kasirin
    image: nginx:stable-alpine
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:80

  app:
    networks:
      - kasirin
    build:
      context: ./src/.
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:9000

  db:
    networks:
      - kasirin
    image: mysql:latest
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=kasirin
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
    ports:
      - 3306:3306
